{"name": "test_select_model_and_send_prompt", "status": "failed", "statusDetails": {"message": "AssertionError: Model 'gemma3:1b' not found in dialog", "trace": "self = <test_example.ChatFlowTest testMethod=test_select_model_and_send_prompt>\n\n    def test_select_model_and_send_prompt(self):\n        chat = ChatPage(self.driver, self.base_url).open()\n    \n        # Select model\n>       chat.select_model(\"gemma3:1b\")\n\ntests/test_example.py:30: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npages/chat_page.py:23: in select_model\n    self.open_model_dialog().select_model(model_name)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <pages.components.model_dialog.ModelDialog object at 0x75130a93d5e0>, name = 'gemma3:1b'\n\n    def select_model(self, name: str):\n        self.wait_loaded()\n        buttons = self.all(self.OPTIONS)\n        target = next((b for b in buttons if b.text.strip() == name), None)\n        if not target:\n>           raise AssertionError(f\"Model '{name}' not found in dialog\")\nE           AssertionError: Model 'gemma3:1b' not found in dialog\n\npages/components/model_dialog.py:17: AssertionError"}, "start": 1755678528652, "stop": 1755678534822, "uuid": "b743e3bb-67d0-42df-a66d-6d9051bd8220", "historyId": "aabeaa2533b67fd8e31c7ad25178ee57", "testCaseId": "aabeaa2533b67fd8e31c7ad25178ee57", "fullName": "tests.test_example.ChatFlowTest#test_select_model_and_send_prompt", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_example"}, {"name": "subSuite", "value": "ChatFlowTest"}, {"name": "host", "value": "LAPTOP-J12RM8I3"}, {"name": "thread", "value": "166416-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_example"}], "titlePath": ["tests", "test_example.py", "ChatFlowTest"]}